import React, { useEffect, useState } from 'react';
import { ArrowRight, ChevronLeft, ChevronRight, Heart, ShieldCheck, Sparkles, Truck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'motion/react';
import { ProductCard } from '../components/ProductCard';
import { useProducts } from '../context/ProductContext';
import { Product } from '../types';

const editorialImages = [
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1600&q=85',
  'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1600&q=85',
  'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1600&q=85'
];

export const Home: React.FC = () => {
  const { products, homeContent, coupons, categories } = useProducts();
  const [slide, setSlide] = useState(0);
  useEffect(() => { window.scrollTo(0, 0); const timer = window.setInterval(() => setSlide(value => (value + 1) % editorialImages.length), 6000); return () => window.clearInterval(timer); }, []);
  const activeCoupon = coupons.find(coupon => coupon.active);
  return <main className="bg-[#fbf8f6] min-h-screen pb-16">
    <section className="relative h-[520px] md:h-[650px] overflow-hidden bg-[#351d28] text-white">{editorialImages.map((image, index) => <motion.img key={image} initial={{ opacity: 0 }} animate={{ opacity: slide === index ? 1 : 0, scale: slide === index ? 1.04 : 1 }} transition={{ duration: 1.1 }} src={image} alt="Suit Aura Girls collection" className="absolute inset-0 w-full h-full object-cover object-center" />)}<div className="absolute inset-0 bg-gradient-to-r from-[#351d28]/85 via-[#351d28]/45 to-transparent" /><div className="relative max-w-7xl mx-auto h-full flex items-center px-6 md:px-12"><div className="max-w-xl"><p className="text-[#e7bd78] text-xs uppercase tracking-[0.3em] mb-5">{homeContent.badge || 'Suit Aura Girls'}</p><h1 className="font-serif text-5xl md:text-7xl leading-[1.05]">{homeContent.title || 'Elegance That Feels Like You'} {homeContent.highlight && <span className="text-[#e7bd78]">{homeContent.highlight}</span>}</h1>{homeContent.subtitle && <p className="text-white/80 text-base md:text-lg mt-6 max-w-lg">{homeContent.subtitle}</p>}<Link to="/shop" className="inline-flex items-center gap-3 mt-8 bg-[#e7bd78] text-[#351d28] px-7 py-3.5 text-sm font-bold hover:bg-[#f0cf96] transition-colors">{homeContent.buttonLabel || 'Explore collection'} <ArrowRight size={18} /></Link></div></div><button onClick={() => setSlide((slide + editorialImages.length - 1) % editorialImages.length)} title="Previous banner" className="absolute left-4 md:left-8 bottom-8 p-3 border border-white/40 hover:bg-white/15"><ChevronLeft size={19} /></button><button onClick={() => setSlide((slide + 1) % editorialImages.length)} title="Next banner" className="absolute left-16 md:left-20 bottom-8 p-3 border border-white/40 hover:bg-white/15"><ChevronRight size={19} /></button><div className="absolute right-6 md:right-12 bottom-10 flex gap-2">{editorialImages.map((_, index) => <button key={index} onClick={() => setSlide(index)} title={`Show banner ${index + 1}`} className={`h-1.5 transition-all ${slide === index ? 'w-10 bg-[#e7bd78]' : 'w-4 bg-white/50'}`} />)}</div></section>
    {activeCoupon && <section className="max-w-7xl mx-auto px-4 -mt-7 relative z-10"><Link to="/checkout" className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-white border border-[#eadfe0] shadow-[0_12px_28px_rgba(90,32,57,0.1)] px-6 py-5 hover:border-[#d9a7b7] transition-colors"><span><span className="text-xs uppercase tracking-[0.18em] text-[#9d3658]">Private offer</span><span className="block text-sm md:text-base text-[#351d28] mt-1">Save {activeCoupon.discountPercent}% on prepaid orders above ₹{activeCoupon.minimumOrder.toLocaleString('en-IN')}</span></span><span className="border border-[#d9a7b7] px-4 py-2 text-xs font-bold tracking-[0.18em] text-[#9d3658]">{activeCoupon.code}</span></Link></section>}
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14"><div className="flex items-end justify-between mb-7"><div><p className="text-xs uppercase tracking-[0.22em] text-[#9d3658]">Curated wardrobe</p><h2 className="font-serif text-3xl md:text-4xl text-[#2b1a21] mt-2">Shop by category</h2></div><Link to="/shop" className="hidden sm:flex items-center gap-2 text-sm text-[#9d3658]">View all <ArrowRight size={16} /></Link></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-5">{categories.map((category, index) => <Link key={category} to={`/shop?category=${encodeURIComponent(category)}`} className="group relative aspect-[4/5] overflow-hidden bg-[#f8e8ed]"><img src={products.find(product => product.category === category)?.images[0] || editorialImages[index % editorialImages.length]} alt={category} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" /><div className="absolute inset-0 bg-gradient-to-t from-[#351d28]/80 via-transparent to-transparent" /><span className="absolute bottom-5 left-5 right-3 text-white font-serif text-xl md:text-2xl">{category}</span></Link>)}</div></section>
    <ProductRail title="New arrivals" eyebrow="Fresh off the loom" products={products.filter(product => product.isNewArrival)} link="/trending" />
    {categories.map(category => <div key={category}><ProductRail title={category} eyebrow="Curated for you" products={products.filter(product => product.category === category).slice(0, 5)} link={`/shop?category=${encodeURIComponent(category)}`} /></div>)}
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14"><div className="grid md:grid-cols-2 gap-5"><div className="relative min-h-[300px] overflow-hidden bg-[#690833] text-white p-8 md:p-12 flex items-end"><img src={editorialImages[1]} alt="Festive collection" className="absolute inset-0 w-full h-full object-cover opacity-35" /><div className="relative"><p className="text-[#e7bd78] text-xs uppercase tracking-[0.22em]">Festive edit</p><h2 className="font-serif text-4xl mt-3">Celebrate in colour.</h2><Link to="/shop?category=Festive%20Wear" className="inline-flex items-center gap-2 mt-6 text-sm text-[#e7bd78]">Shop festive wear <ArrowRight size={16} /></Link></div></div><div className="relative min-h-[300px] overflow-hidden bg-[#f3dfe4] p-8 md:p-12 flex items-end"><img src={editorialImages[2]} alt="Everyday collection" className="absolute inset-0 w-full h-full object-cover opacity-25" /><div className="relative text-[#351d28]"><p className="text-[#9d3658] text-xs uppercase tracking-[0.22em]">Everyday luxury</p><h2 className="font-serif text-4xl mt-3">Made for your moments.</h2><Link to="/shop?category=Kurtis" className="inline-flex items-center gap-2 mt-6 text-sm text-[#9d3658]">Explore kurtis <ArrowRight size={16} /></Link></div></div></div></section>
    <ProductRail title="Best sellers" eyebrow="Most cherished" products={products.filter(product => product.isBestSeller)} link="/shop" />
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-14"><div className="relative overflow-hidden bg-[#690833] text-white min-h-[360px] flex items-center"><img src={editorialImages[0]} alt="The Aura Sale collection" className="absolute inset-0 w-full h-full object-cover opacity-30" /><div className="relative p-8 md:p-14 max-w-xl"><p className="text-[#e7bd78] text-xs uppercase tracking-[0.28em]">The Aura Sale</p><h2 className="font-serif text-4xl md:text-5xl mt-4">A little more joy in every detail.</h2><p className="text-white/75 mt-4">Explore selected styles at considered prices. Every product shown is available through the live catalogue.</p><Link to="/shop?sale=true" className="inline-flex items-center gap-2 mt-7 bg-[#e7bd78] text-[#351d28] px-6 py-3 text-sm font-semibold">Explore sale <ArrowRight size={17} /></Link></div></div></section>
    <section className="border-y border-[#eadfe0] bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 grid grid-cols-1 md:grid-cols-3 gap-8"><Trust icon={ShieldCheck} title="Prepaid secure checkout" text="Protected online payments through Razorpay." /><Trust icon={Truck} title="Tracked delivery" text="Follow every verified order from dispatch to doorstep." /><Trust icon={Heart} title="Made with intention" text="Thoughtful silhouettes for your everyday and festive wardrobe." /></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14"><div className="flex items-end justify-between mb-7"><div><p className="text-xs uppercase tracking-[0.22em] text-[#9d3658]">The promise</p><h2 className="font-serif text-3xl md:text-4xl text-[#2b1a21] mt-2">A considered shopping experience.</h2></div><Link to="/about" className="hidden sm:flex items-center gap-2 text-sm text-[#9d3658]">Our story <ArrowRight size={16} /></Link></div><div className="grid md:grid-cols-3 gap-5"><Promise number="01" title="Quality checked" text="Every live catalogue entry can carry its own fabric, fit and care details." /><Promise number="02" title="Prepaid only" text="UPI, cards and net banking are handled through the secure payment gateway." /><Promise number="03" title="Order visibility" text="Once payment is verified, each order moves through an admin-controlled timeline." /></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-14"><div className="flex items-end justify-between mb-7"><div><p className="text-xs uppercase tracking-[0.22em] text-[#9d3658]">Follow the aura</p><h2 className="font-serif text-3xl md:text-4xl text-[#2b1a21] mt-2">A lookbook for your next occasion.</h2></div><Link to="/shop" className="hidden sm:flex items-center gap-2 text-sm text-[#9d3658]">Shop all <ArrowRight size={16} /></Link></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{editorialImages.concat(editorialImages[1]).map((image, index) => <Link to={`/shop?category=${encodeURIComponent(categories[index % categories.length] || 'Suits')}`} key={`${image}-${index}`} className="group relative aspect-square overflow-hidden bg-[#f8e8ed]"><img src={image} alt="Suit Aura Girls lookbook" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" /><span className="absolute bottom-3 left-3 text-white text-xs font-semibold drop-shadow">Explore look {index + 1}</span></Link>)}</div></section>
    <section className="max-w-3xl mx-auto text-center px-5 py-16"><Sparkles className="mx-auto text-[#9d3658]" size={22} /><h2 className="font-serif text-4xl text-[#2b1a21] mt-4">Stay close to the aura.</h2><p className="text-neutral-500 mt-3">Get new collection updates and private offers in your inbox.</p><form className="flex gap-2 mt-7" onSubmit={event => { event.preventDefault(); alert('Thank you for joining Suit Aura Girls.'); }}><input required type="email" placeholder="Your email address" className="min-w-0 flex-1 border border-[#eadfe0] px-4 py-3 outline-none focus:border-[#9d3658]" /><button className="bg-[#690833] text-white px-5 py-3 text-sm">Join us</button></form></section>
  </main>;
};

function ProductRail({ title, eyebrow, products, link }: { title: string; eyebrow: string; products: Product[]; link: string }) { return <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-14"><div className="flex items-end justify-between mb-7"><div><p className="text-xs uppercase tracking-[0.22em] text-[#9d3658]">{eyebrow}</p><h2 className="font-serif text-3xl md:text-4xl text-[#2b1a21] mt-2">{title}</h2></div><Link to={link} className="flex items-center gap-2 text-sm text-[#9d3658]">Explore <ArrowRight size={16} /></Link></div>{products.length ? <div className="flex gap-4 overflow-x-auto snap-x snap-mandatory pb-4">{products.map(product => <div key={product.id} className="min-w-[220px] sm:min-w-[245px] md:min-w-0 md:w-1/4 snap-start"><ProductCard product={product} /></div>)}</div> : <div className="border border-dashed border-[#eadfe0] py-12 text-center text-sm text-neutral-500">New styles will appear here after catalogue updates.</div>}</section>; }
function Trust({ icon: Icon, title, text }: { icon: React.ElementType; title: string; text: string }) { return <div className="flex gap-4"><Icon className="text-[#9d3658] shrink-0" size={24} /><div><h3 className="font-semibold text-[#2b1a21]">{title}</h3><p className="text-sm text-neutral-500 mt-1">{text}</p></div></div>; }
function Promise({ number, title, text }: { number: string; title: string; text: string }) { return <div className="border-t border-[#eadfe0] pt-5"><span className="text-xs tracking-[0.2em] text-[#9d3658]">{number}</span><h3 className="font-serif text-2xl text-[#2b1a21] mt-3">{title}</h3><p className="text-sm text-neutral-500 mt-2 leading-relaxed">{text}</p></div>; }
